name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    - name: Godot Export
      uses: firebelley/godot-export@v1.0.0
      with:
        # Base version. Patch versions are incremented when this action runs.
        base_version: 0.0.1
        # The download url of the 64 bit Linux Headless Godot executable
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.1.2/Godot_v3.1.2-stable_linux_headless.64.zip
        # The url of the export templates corresponding to the Godot executable version
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.1.2/Godot_v3.1.2-stable_export_templates.tpz
        # The relative path containing the "project.godot" file
        relative_project_path: .
        # The name of the folder which templates are stored in. Looks like '3.1.1.stable.mono'. Can be found at %APPDATA\Roaming\Godot\templates on Windows and ~/.local/share/godot/templates on Linux.
        godot_template_version: 3.1.2.stable
